const memeDatabase = {
  noob: [
    "Me, trying to teammates steal your loot",
    "That moment you get reported for being too good",
    "That moment you camp with style",
    "Nothing hits harder than carry the entire squad",
    "That moment you get spawn killed 3 times in a row",
    "Welcome to try to flex with hacks",
    "When you lag right before the clutch",
    "Me, trying to win with 1 HP",
    "Actual footage of glitch through the wall",
    "Welcome to get caught cheating live on stream",
    "Welcome to join a clan and regret it",
    "That moment you join a clan and regret it",
    "Actual footage of win with 1 HP",
    "You know it’s bad when win with 1 HP",
    "When you AFK during the final boss",
    "Just another day of AFK during the final boss",
    "Me, trying to camp with style",
    "When you grind 6 hours for a gray item",
    "POV: glitch through the wall",
    "The face you make when grind 6 hours for a gray item",
    "The face you make when get spawn killed 3 times in a row",
    "When you try to flex with hacks",
    "Actual footage of get spawn killed 3 times in a row",
    "Just another day of get headshotted mid-jump",
    "The face you make when try to flex with hacks",
    "The face you make when win with 1 HP",
    "Just another day of miss every shot",
    "When you fight a level 999 boss",
    "Welcome to lag right before the clutch",
    "Me, trying to accidentally throw a grenade",
    "Welcome to camp with style",
    "Actual footage of get caught cheating live on stream",
    "Welcome to grind 6 hours for a gray item",
    "Me, trying to try to flex with hacks",
    "Just another day of miss every shot"
  ],
  rage: [
    "That moment you get spawn killed 3 times in a row",
    "Just another day of rage quit before the cutscene",
    "POV: fight a level 999 boss",
    "Actual footage of miss every shot",
    "Me, trying to get caught cheating live on stream",
    "That moment you get caught cheating live on stream",
    "You know it’s bad when lag right before the clutch",
    "Nothing hits harder than get headshotted mid-jump",
    "When you glitch through the wall",
    "That moment you miss every shot",
    "Me, trying to go full sweat mode",
    "That moment you carry the entire squad",
    "Nothing hits harder than win with 1 HP",
    "Nothing hits harder than camp with style",
    "The face you make when AFK during the final boss",
    "That moment you get reported for being too good",
    "Me, trying to accidentally throw a grenade",
    "That moment you get headshotted mid-jump",
    "The face you make when camp with style",
    "When you accidentally throw a grenade"
  ],
  camping: [
    "Me, trying to win with 1 HP",
    "The face you make when glitch through the wall",
    "The face you make when AFK during the final boss",
    "Just another day of try to flex with hacks",
    "POV: camp with style",
    "Nothing hits harder than grind 6 hours for a gray item",
    "That moment you grind 6 hours for a gray item",
    "You know it’s bad when lag right before the clutch",
    "Actual footage of carry the entire squad",
    "Welcome to win with 1 HP",
    "That moment you get spawn killed 3 times in a row",
    "Actual footage of join a clan and regret it",
    "Me, trying to get spawn killed 3 times in a row",
    "Nothing hits harder than go full sweat mode",
    "When you reload at the wrong time",
    "That moment you camp with style",
    "Actual footage of glitch through the wall",
    "Welcome to reload at the wrong time",
    "Me, trying to accidentally throw a grenade",
    "Just another day of miss every shot"
  ],
  clutch: [
    "The face you make when teammates steal your loot",
    "The face you make when miss every shot",
    "You know it’s bad when carry the entire squad",
    "Nothing hits harder than fight a level 999 boss",
    "That moment you AFK during the final boss",
    "That moment you accidentally throw a grenade",
    "Just another day of join a clan and regret it",
    "Welcome to get headshotted mid-jump",
    "Actual footage of miss every shot",
    "Actual footage of go full sweat mode",
    "Me, trying to accidentally throw a grenade",
    "Nothing hits harder than reload at the wrong time",
    "POV: carry the entire squad",
    "Nothing hits harder than accidentally throw a grenade",
    "When you go full sweat mode",
    "You know it’s bad when lag right before the clutch",
    "The face you make when get reported for being too good",
    "POV: AFK during the final boss"
  ],
  lag: [
    "POV: camp with style",
    "Me, trying to fight a level 999 boss",
    "POV: miss every shot",
    "You know it’s bad when try to flex with hacks",
    "When you lag right before the clutch",
    "Actual footage of join a clan and regret it",
    "Welcome to teammates steal your loot",
    "When you rage quit before the cutscene",
    "Just another day of grind 6 hours for a gray item",
    "That moment you carry the entire squad",
    "Nothing hits harder than get reported for being too good",
    "Nothing hits harder than fight a level 999 boss",
    "Nothing hits harder than get caught cheating live on stream",
    "That moment you get spawn killed 3 times in a row",
    "Welcome to camp with style",
    "The face you make when rage quit before the cutscene",
    "POV: try to flex with hacks",
    "Welcome to reload at the wrong time"
  ],
  teammates: [
    "Welcome to get reported for being too good",
    "Me, trying to rage quit before the cutscene",
    "Actual footage of get headshotted mid-jump",
    "Welcome to lag right before the clutch",
    "Welcome to go full sweat mode",
    "That moment you accidentally throw a grenade",
    "When you AFK during the final boss",
    "Nothing hits harder than teammates steal your loot",
    "The face you make when you carry the entire squad",
    "Just another day of grind 6 hours for a gray item"
  ],
  spawnkill: [
    "That moment you try to flex with hacks",
    "The face you make when carry the entire squad",
    "Nothing hits harder than teammates steal your loot",
    "That moment you get spawn killed 3 times in a row",
    "Nothing hits harder than lag right before the clutch",
    "Just another day of AFK during the final boss",
    "When you respawn into instant death",
    "Me, trying to run but getting spawn killed again",
    "Welcome to a life of pain",
    "Actual footage of frustration loading..."
  ],
  "1hp": [
    "The face you make when teammates steal your loot",
    "That moment you fight a level 999 boss",
    "Nothing hits harder than get headshotted mid-jump",
    "You know it’s bad when get headshotted mid-jump",
    "Actual footage of surviving on vibes",
    "When you sneeze and almost die",
    "Barely breathing, still clutching",
    "POV: You’re on your last pixel",
    "Health bar? Never heard of her",
    "Just another day at 1 HP"
  ],
  afk: [
    "Me, trying to AFK during the final boss",
    "POV: rage quit before the cutscene",
    "When you get caught cheating live on stream",
    "The face you make when grind 6 hours for a gray item",
    "Welcome to get reported for being too good",
    "That moment you come back and everything’s on fire",
    "AFK = Already Fired, Kid",
    "Left the match, left the team",
    "Phone rang, game over",
    "Just here to collect XP"
  ],
  headshot: [
    "You know it’s bad when accidentally throw a grenade",
    "The face you make when go full sweat mode",
    "Nothing hits harder than rage quit before the cutscene",
    "Me, trying to fight a level 999 boss",
    "Actual footage of crosshair perfection",
    "One tap, one legend",
    "360 no scope dreams",
    "Click. Boom. Done.",
    "Bullet with your name on it",
    "Headshot machine online"
  ],
  loot: [
    "When you carry the entire squad",
    "Actual footage of teammates steal your loot",
    "Nothing hits harder than accidentally throw a grenade",
    "Me, trying to get reported for being too good",
    "That moment you rage quit before the cutscene",
    "When your friend opens the chest you spotted first",
    "Me, staring at a legendary drop... they took",
    "Loot goblins be like: mine mine mine",
    "POV: You got a gray item after a boss fight",
    "Steals kill, steals loot, steals glory"
  ],
  grind: [
    "Welcome to go full sweat mode",
    "Me, trying to carry the entire squad",
    "Nothing hits harder than teammates steal your loot",
    "That moment you grind 6 hours for a gray item",
    "Actual footage of lost weekends",
    "Grind now, cry later",
    "POV: Level 99 but empty inside",
    "Just one more run... every 30 minutes",
    "Still no rare drop after 43 tries",
    "Me, convincing myself it’s worth it"
  ],
  bossfight: [
    "POV: grind 6 hours for a gray item",
    "When you lag right before the clutch",
    "Welcome to camp with style",
    "Actual footage of glitch through the wall",
    "We’re gonna need a bigger sword",
    "I didn’t sign up for this trauma",
    "One hit and you're gone",
    "Raid boss = friendship test",
    "Giant red bar of doom",
    "When you spend 20 minutes dodging one move"
  ],
  carry: [
    "POV: try to flex with hacks",
    "POV: carry the entire squad",
    "Just another day of get caught cheating live on stream",
    "Me, trying to glitch through the wall",
    "That moment you rage quit before the cutscene",
    "Heavy is the crown of the hard carry",
    "When they do nothing and still talk trash",
    "Tired shoulders from carrying so hard",
    "1v4 and still win",
    "You: stats. Them: vibes"
  ],
  glitch: [
    "Just another day of AFK during the final boss",
    "Me, trying to accidentally throw a grenade",
    "Actual footage of physics taking a break",
    "When the wall isn’t real anymore",
    "My body is here, my soul is elsewhere",
    "Teleporting with style",
    "Reality.exe has stopped working",
    "Perfect timing = broken map",
    "Game logic left the chat",
    "Laughing through the lag tears"
  ],
  toxic: [
    "Me, trying to accidentally throw a grenade",
    "Welcome to join a clan and regret it",
    "Nothing hits harder than glitch through the wall",
    "You know it’s bad when win with 1 HP",
    "Mic on. Regret instantly.",
    "They typed before the match started",
    "Salt levels over 9000",
    "Chat logs the judge would read",
    "When 'GG' means 'Get Good'",
    "That one player who ruins it for all"
  ],
  clan: [
    "You know it’s bad when join a clan and regret it",
    "Me, trying to get caught cheating live on stream",
    "That moment you camp with style",
    "Just another day in dysfunctional family chat",
    "Clan wars: 1% tactics, 99% drama",
    "Welcome to the group text from hell",
    "Why do I need 8 meetings a week?",
    "When your clan leader thinks they’re CEO",
    "Joined for loot, stayed for pain",
    "POV: Left the clan and felt free"
  ],
  sweat: [
    "Welcome to get headshotted mid-jump",
    "Nothing hits harder than join a clan and regret it",
    "Actual footage of teammates steal your loot",
    "You know it’s bad when carry the entire squad",
    "Just another day of reload at the wrong time",
    "Tryhard detected",
    "Sweating in casual mode",
    "The warmup is a championship game to them",
    "Stretching before keyboard tryouts",
    "Gym? No — ranked queue."
  ],
  cheater: [
    "You know it’s bad when reload at the wrong time",
    "Me, trying to lag right before the clutch",
    "POV: miss every shot",
    "POV: get headshotted mid-jump",
    "POV: win with 1 HP",
    "You can't spell 'suspicious' without 'us'",
    "Snapped to head... again",
    "Reported before the match ended",
    "Hackerman returns",
    "Console players confused"
  ],
  victory: [
    "Actual footage of win with 1 HP",
    "Actual footage of go full sweat mode",
    "You know it’s bad when accidentally throw a grenade",
    "Just another day of glitch through the wall",
    "We did it... but at what cost?",
    "Victory Royale or anxiety simulator?",
    "The silence after a loud win",
    "High score, low life",
    "The W feels good. The sleep deprivation doesn’t.",
    "Screenshot or it didn’t happen"
  ]
};


// Core logic: generates a random title based on tag
function generateTitle(tag) {
  const titles = memeDatabase[tag];
  if (!titles || titles.length === 0) {
    document.getElementById("titleResult").innerText = "No titles available yet for this tag!";
    return;
  }

  const randomIndex = Math.floor(Math.random() * titles.length);
  const title = titles[randomIndex];

  document.getElementById("titleResult").innerText = title;
}
